conversation/urls.py
from django.urls import path



from . import views


app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('singup/', views.singup, name='singup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browse, name='items'),
    path("new/", views.new, name="new"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("inbox/", include('conversation.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('name',)

    def __str__(self) -> str:
        return self.name


class Item(models.Model):
    category = models.ForeignKey(
        Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name='items', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewItemFrom(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'}),
            'name': forms.TextInput(attrs={'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'}),
            'description': forms.Textarea(attrs={'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'}),
            'price': forms.TextInput(attrs={'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'}),
            'image': forms.FileInput(attrs={'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'}),
        }


class EditItemFrom(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': 'w-full py-2 px-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-blue-400'  # Corrected class here
            })
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .forms import NewItemFrom, EditItemFrom
from .models import Item, Category

# Create your views here.


def browse(request):
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) |
                             Q(description__icontains=query))
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(
        category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemFrom(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemFrom()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemFrom(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemFrom(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %} {% block title %}{{ item.name }}{% endblock %} 
{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    {% if item.image %}
    <img src="{{ item.image.url }}" alt="Item image" class="mx-auto h-full object-cover" style="height: 550px;">
    {% else %}
      <div class="w-full h-full flex items-center justify-center bg-gray-300"style="height: 550px;">
        <span class="fas fa-camera fa-5x text-gray-500">📷</span>
      </div>
    {% endif %}
  </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-500"><strong>Price: </strong> {{ item.price }}</p>
    <p class="text-gray-500">
      <strong>Seller: </strong> {{ item.created_by.username }}
    </p>

    {% if item.description %}
    <p class="text-gray-700">
      <strong class="text-gray-500">Description: </strong><br />
      {{ item.description }}
    </p>
    {% endif %} {% if request.user == item.created_by %}
    <div class="mt-6 p-6 bg-white rounded-xl">
      <p>This is your item!</p>
      <a
        href="{% url 'item:edit' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl"
        >Edit</a
      >
      <a
        href="{% url 'item:delete' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl"
        >Delete</a
      >
    </div>

    {% else %}
    <a href="{% url 'conversation:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 rounded-xl text-white hover:bg-teal-700"
      >Contact seller</a>
    {% endif %}
  </div>
</div>

<div class="mt-6  px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class=" text-2xl text-center">Related items</h2>
  <div class="grid grid-cols-3 gap-3">
    {% for i in related_items %}
    <div>
      <a href="{% url 'item:detail' i.id %}">
        <div class="bg-white rounded-t-xl overflow-hidden h-80">
          {% if i.image %}
          <img src="{{ i.image.url }}" alt="Item image" class="mx-auto h-full object-cover">
          {% else %}
            <div class="w-full h-full flex items-center justify-center bg-gray-300">
              <span class="fas fa-camera fa-5x text-gray-500">📷</span>
            </div>
          {% endif %}
        </div>
        <div class="p-6 bg-white rounded-b-xl ">
          <h2 class="text-2xl">{{ i.name }}</h2>
          <p class="text-gray-500">Price: {{ i.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>




{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %}Create a New Item{% endblock %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Create a New Item</h2>
  <form method="post" class="w-full max-w-md mx-auto" enctype="multipart/form-data">

    {{ form.errors }}

    <div class="mb-4">
      {{ form.category.label_tag }}
      {{ form.category }}
    </div>
    
    <div class="mb-4">
      {{ form.name.label_tag }}
      {{ form.name }}
    </div>
    
    <div class="mb-4">
      {{ form.description.label_tag }}
      {{ form.description }}
    </div>
    
    <div class="mb-4">
      {{ form.price.label_tag }}
      {{ form.price }}
    </div>
    
    <div class="mb-4">
      {{ form.image.label_tag }}
      {{ form.image }}
    </div>
    
    {% csrf_token %}

    <button class="mt-6 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline" type="submit">
      Create Item
    </button>

  </form>
</div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}
{% block title %} Browse {% endblock %}
{% block content %}

<div class="pb-6 pl-3 h-auto pt-3 grid grid-cols-4 gap-4 bg-gray-100 rounded-xl">
  <div class="col-span-1">
    <form action="{% url 'item:items' %}" method="get">
      <input
        type="text"
        name="query"
        class="w-full py-4 px-6 border rounded-xl"
        value="{{ query }}"
        placeholder="Browse"
      />
      <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">
        Search
      </button>
    </form>
    <hr class="my-6" />

    <p class="font-semibold">Categories</p>
    <ul>
      {% for c in categories %}
      <li
        class="py-2 px-2 rounded-xl {% if c.id == category_id %} bg-gray-200 {% endif %}"
      >
        <a href="{% url 'item:items' %}?query={{ query }}&category={{ c.id }}">
          {{ c.name }}
        </a>
      </li>
      {% endfor %}
    </ul>
    <hr class="my-6" />

    <p class="font-semibold">Clear filters</p>
    <ul>
      <li>
        <a
          href="{% url 'item:items' %}"
          class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white"
        >
          Clear
        </a>
      </li>
    </ul>
  </div>
  <div class="col-span-3">
    <div class="grid grid-cols-3 gap-3">
      {% for i in items %}
      <div>
        <a href="{% url 'item:detail' i.id %}">
          <div class="bg-white rounded-t-xl overflow-hidden h-96">
            {% if i.image %}
            <img src="{{ i.image.url }}" alt="item" class="mx-auto h-full object-cover" />
            {% else %}
            <div class="w-full h-full flex items-center justify-center bg-gray-300">
              <span class="fas fa-camera fa-5x text-gray-500">📷</span>
            </div>
            {% endif %}
          </div>
          <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{ i.name }}</h2>
            <p class="text-gray-500">Price: {{ i.price }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}